// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iqenvhlrfziqblwnoxko.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlxZW52aGxyZnppcWJsd25veGtvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzMDMxMzEsImV4cCI6MjA3Mzg3OTEzMX0.Eu-iHdcUuXXDqYYuYKmj5b_QU22FTX6AZmsp81qRZL4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});